version: '3'

services:
  envoy-transcoder:
    container_name: envoy-transcoder
    image: envoyproxy/envoy:v1.20.6
    volumes:
      - ./transcoder/:/etc/envoy/
    expose:
      - "51051"
      - "9901"
    ports:
      - "51051:51051"
      - "9901:9901"
    extra_hosts:
      - "host.docker.internal:host-gateway"